[package]
name = "nyar_python"
version = "0.0.1"
authors = ["192608617@qq.com"]
edition = "2018"
description = "..."
license = "MPL-2.0"


[dependencies]
nyar_valkyrie = "0.0.2"

[dev-dependencies]


[build-dependencies]
